# Generated by Django 4.2.6 on 2023-10-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('Brisbane', 'Brisbane'), ('Sydney', 'Sydney'), ('Melbourne', 'Melbourne'), ('Perth', 'Perth'), ('Canberra', 'Canberra'), ('Darwin', 'Darwin'), ('Tasmania', 'Tasmania')], max_length=20)),
                ('intake', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('application_date_start', models.DateTimeField()),
                ('application_date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_mobile', models.IntegerField()),
                ('scholarship_amount', models.IntegerField()),
                ('number_available', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('contact_mobile', models.IntegerField()),
                ('home_city', models.CharField(max_length=200)),
                ('pronouns', models.CharField(max_length=200)),
                ('qualities', models.TextField()),
                ('location', models.CharField(choices=[('Brisbane', 'Brisbane'), ('Sydney', 'Sydney'), ('Melbourne', 'Melbourne'), ('Perth', 'Perth'), ('Canberra', 'Canberra'), ('Darwin', 'Darwin'), ('Tasmania', 'Tasmania')], max_length=20)),
                ('reason', models.TextField()),
                ('previous_education', models.CharField(max_length=200)),
                ('work_experience', models.TextField()),
                ('currently_employed', models.BooleanField()),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField()),
                ('gender_eligible', models.BooleanField(blank=True, null=True)),
                ('resume', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Shortlist', 'Shortlist'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Successful', 'Successful'), ('Scholarship Assigned', 'Scholarship Assigned')], default='New', max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='program.program')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_scholarship', to='program.scholarship')),
            ],
        ),
    ]
