# Generated by Django 4.2.6 on 2023-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
