# Generated by Django 4.2.6 on 2023-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_applicant_gender_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='home_city',
            field=models.CharField(default='Brisbane', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='pronouns',
            field=models.CharField(default='She/her', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='qualities',
            field=models.TextField(default='community changer'),
            preserve_default=False,
        ),
    ]
